### ISSUE TITLE
Add a feature to download audio too.

### ISSUE THREAD

**Issue by aryanA101a** [aryanfluxion/Youtube-Video-Downloader#2]
You have to work on both back end and front end.

**Comment by ashvinimore** [comment]
Hello Aryan,
We have to build a feature to download audio clip from Youtube itself with frontened same as you did for Video Downloader?
Thank You

**Comment by kennethgargan** [comment]
Hi, Can I be assigned this?

**Comment by aryanA101a** [comment]
> Hello Aryan,
> We have to build a feature to download audio clip from Youtube itself with frontened same as you did for Video Downloader?
> Thank You

@ashvinimore Yes

**Comment by aryanA101a** [comment]
> Hi, Can I be assigned this?

We don't assigned, anyone can work 😊

**Comment by ashvinimore** [comment]
> Yes

Thank you Aryan .I will start my work then.

**Comment by aryanA101a** [comment]
> > Yes
> 
> Thank you Aryan .I will start my work then.

Best of luck😊

**Comment by ashvinimore** [comment]
Hello Aryan,
I have completed the task.
Please review it.
Thank You
